### ISSUE TITLE
Open postrgresql Logo is not good with retina display

### ISSUE THREAD

**Issue by masseuro** [OPMDG/opm-core#12]
Not really important, but some disturb during use
![capture d ecran 2014-10-30 a 16 32 35](https://cloud.githubusercontent.com/assets/131135/4846182/10e83398-604a-11e4-8cec-ff456451089d.png)

**Comment by daamien** [comment]
Hi @masseuro : We don't have any retina screen nearby. Before we push a fix, can you check that the image below is displayed correctly ?

http://nawak.taadeem.net/test_opm_logo_retina.html

**Comment by masseuro** [comment]
it's perfect, thank you.
<img width="246" alt="capture d ecran 2016-07-21 a 09 44 50" src="https://cloud.githubusercontent.com/assets/131135/17014971/d29ac1cc-4f27-11e6-9fcd-e150192f4f26.png">

**Comment by rjuju** [comment]
Thanks for the feedback!

We'll integrate it in the next release.
