### ISSUE TITLE
Couldn't load application from file "script/opm": Type of arg 1 to push must be array (not private variable) at /usr/local/src/opm/opm-core

### ISSUE THREAD

**Issue by khumeshturkar** [OPMDG/opm-core#15]
After installation of OPM on CentOS release 6.6 (Final) getting below error. 
 
morbo script/opm
[Tue Mar 24 14:15:47 2015] [debug] Reading configuration file "/usr/local/src/opm/opm-core-REL_2_3/ui/opm.conf".
[Tue Mar 24 14:15:47 2015] [debug] Helper "url_for" already exists, replacing.
Couldn't load application from file "script/opm": Type of arg 1 to push must be array (not private variable) at /usr/local/src/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios/Nagios.pm line 20, near ")"
Type of arg 1 to push must be array (not private variable) at /usr/local/src/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios/Nagios.pm line 26, near ")"
Compilation failed in require at /usr/local/src/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios.pm line 97.
BEGIN failed--compilation aborted at /usr/local/src/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios.pm line 97.
Compilation failed in require at (eval 277) line 1.

**Comment by ioguix** [comment]
Hi,

What version of Mojolicious do you use ?

**Comment by khumeshturkar** [comment]
Hi ioguix,
Below are the details for mojolicious.
----------------------------------------------------------------
mojo version
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (4.99, Top Hat)

OPTIONAL
  EV 4.0+               (not installed)
  IO::Socket::IP 0.20+  (not installed)
  IO::Socket::SSL 1.84+ (not installed)
--------------------------------------------------------------------

**Comment by ioguix** [comment]
Hi,

Your Perl version is probably too old.

I know rjuju have some patch around about perm 5.10, I'll ping him to check if he could commit them. In the mean time, maybe you should upgrade your perl version.

Thank you,

**Comment by khumeshturkar** [comment]
Thanks you so much for quick reply! I will update perl version and let you know the outcome.

Thank you,
Khumesh

**Comment by khumeshturkar** [comment]
While tried installing perl it shows you are at latest version
 yum -y install perl
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
Package 4:perl-5.10.1-136.el6_6.1.x86_64 already installed and latest version
Nothing to do
Please suggest if I am missing anything. Thanks in advance!

**Comment by khumeshturkar** [comment]
After upgrading perl version, the issue is not resolved. Please suggest!
