### ISSUE TITLE
Default parameters template for metrics

### ISSUE THREAD

**Issue by mrimbault** [OPMDG/opm-core#22]
Hi,

It would be interesting to provide a way to set a "graph template" for a metrics family.
For example, metrics like backends number, databases size or wal files number are usually more interesting when stacked.
This template could also be used to disable by default some series (like "total_wal" for the wal files metric if stacked).

**Comment by rjuju** [comment]
Done in commit f2ce7dc19a43020ae91df58e388d0f39b40a2d66.
