### ISSUE TITLE
404 link in page at http://demo.opm.io/about

### ISSUE THREAD

**Issue by jmscott** [OPMDG/opm-core#29]
In the page

       https://github.com/dalibo/OPM/wiki

getting a 404 error for the link in

        https://github.com/dalibo/OPM/wiki

in the anchor "Visit official website for more information.".

**Comment by rjuju** [comment]
Hello,

Thanks for the report. This has already been fixed in commit https://github.com/OPMDG/opm-core/commit/8fdb243cd90ca2d6190300a8bb774ef26456030a but not released yet. The good URL is http:/opm.io
