### ISSUE TITLE
How to set up Nagios

### ISSUE THREAD

**Issue by FayeG** [OPMDG/opm-core#30]
Hi,

 It seems that check_pgactivity is somehow important to getting stats data of a PostgreSQL database in to opm. However in the installation notes, http://opm.readthedocs.org/opm-core/Installation.html, I can't find a reference to how to put this in to nagios.

Can you help?

**Comment by rjuju** [comment]
Hello,

Yes OPM is based on Nagios. We assume that people who use OPM are already familiar with it, and who may already use it. So if you don't have any knowledge on Nagios, my only advices are to check the nagios documentation to see if that software suits you, and if it doesn't then OPM is probably not a good solution for you. The official nagios documentation is available here : https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/toc.html
