### ISSUE TITLE
Installation notes confusing regarding databases

### ISSUE THREAD

**Issue by FayeG** [OPMDG/opm-core#31]
Hi,

In the document http://opm.readthedocs.org/opm-core/Installation.html which is the database than I want to monitor and which is the database that's holding the opm data used in the UI?

Faye

**Comment by rjuju** [comment]
Database specified in the installation section is the database that will hold the opm data.

There is nothing to install on the monitored database, just setup the probes (check_pgactivity or other ones) for them through Nagios.
