### ISSUE TITLE
what is the wh_nagios warehouse

### ISSUE THREAD

**Issue by FayeG** [OPMDG/opm-core#33]
Hi,

 In the documentation: http://opm.readthedocs.org/opm-core/Installation.html it mentions the wh_nagios warehouse. What is this? Is this a database I need to set up?

When the installation instructions ask me to run: SELECT grant_dispatcher('wh_nagios', 'user1'); 
what is this user1 and how do I know that the "wh_nagios" is the correct value?

**Comment by rjuju** [comment]
wh_nagios is an extension to store the nagios perfdata that you have to install on the OPM database, just as opm. The repository is https://github.com/OPMDG/opm-wh_nagios
