### ISSUE TITLE
Error when installing opm-core

### ISSUE THREAD

**Issue by tabdoelhafiezkhan** [OPMDG/opm-core#36]
Hello,

We tried to install opm on CentOS 6.6. We receive the followning error 

[root@sqlmon1 ui]# pwd
/var/lib/opm/opm-core-REL_2_3/ui

[root@sqlmon1 ui]# morbo script/opm
[Tue Apr  5 14:00:54 2016] [debug] Reading configuration file "/var/lib/opm/opm-core-REL_2_3/ui/opm.conf".
[Tue Apr  5 14:00:54 2016] [debug] Helper "url_for" already exists, replacing.
Couldn't load application from file "script/opm": Type of arg 1 to push must be array (not private variable) at /var/lib/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios/Nagios.pm line 20, near ")"
Type of arg 1 to push must be array (not private variable) at /var/lib/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios/Nagios.pm line 26, near ")"
Compilation failed in require at /var/lib/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios.pm line 97.
BEGIN failed--compilation aborted at /var/lib/opm/opm-core-REL_2_3/ui/modules/wh_nagios/lib/OPM/WhNagios.pm line 97.
Compilation failed in require at (eval 278) line 1.

What could be the reason for this? Hope you can help? Nagios is installed and is working. 
I used these instructions to install: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/quickstart-fedora.html

See also below a list of installed software / packages.

Regards,
Tim

- mojo version

[root@sqlmon1 ui]# mojo version
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (4.99, Top Hat)

OPTIONAL
  EV 4.0+               (not installed)
  IO::Socket::IP 0.20+  (not installed)
  IO::Socket::SSL 1.84+ (not installed)

You might want to update your Mojolicious to 6.57.
[root@sqlmon1 ui]# 

- gd gd-devel

[root@sqlmon1 ui]# rpm -vqa |grep gd
gd-devel-2.0.35-11.el6.x86_64
gd-2.0.35-11.el6.x86_64

- nagios

[root@sqlmon1 ui]# rpm -vqa |grep nagio
nagios-repo-6-2.el6.noarch

- php

[root@sqlmon1 ui]# rpm -vqa |grep php
php-common-5.3.3-46.el6_7.1.x86_64
php-cli-5.3.3-46.el6_7.1.x86_64
php-5.3.3-46.el6_7.1.x86_64

- gcc glibc glib-common

[root@sqlmon1 ui]# rpm -vqa |grep gcc
gcc-4.4.7-11.el6.x86_64
libgcc-4.4.7-11.el6.x86_64
[root@sqlmon1 ui]# rpm -vqa |grep glibc
glibc-devel-2.12-1.149.el6_6.9.x86_64
glibc-2.12-1.149.el6_6.9.x86_64
glibc-headers-2.12-1.149.el6_6.9.x86_64
glibc-common-2.12-1.149.el6_6.9.x86_64

- OS CentOS 6.6

[root@sqlmon1 ui]# uname -a
Linux sqlmon1 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@sqlmon1 ui]# cat /etc/redhat-release 
CentOS release 6.6 (Final)
[root@sqlmon1 ui]#

**Comment by rjuju** [comment]
Hello,

It's a bug in the current version of OPM wit perl 5.10.

If you can't update perl, applying these patches should solve the issue:

  * https://github.com/OPMDG/opm-wh_nagios/commit/35ac66860f52e61a50126c05c1975628b1219e65
  * https://github.com/OPMDG/opm-core/commit/6c93b00de3c5674d9eb262b6891593a84dc036a3

**Comment by tabdoelhafiezkhan** [comment]
Hello rjuju, thanks for your comment.
I'll try it today and upload the results here.

Regards

**Comment by tabdoelhafiezkhan** [comment]
Hello rjuju,
It was a bit busy. I managed to apply the patches and it resolved the problem.
Thanks again. 
Now I can log on to Nagios and OPM, only I can't seem to see any services in OPM. 
I'll continue troubleshooting.

Regards
Tim

**Comment by rjuju** [comment]
Good news!

I started to document the things to verify when UI is up but empty, since it's frequently asked. Can you try it and see if it helps? http://opm.readthedocs.org/general/common_problems.html

Feel free to ask if it doesn't help, it's unclear or if I can improve this documentation.

Regards.

**Comment by tabdoelhafiezkhan** [comment]
Hello rjuju,

I'm a DBA and not familier with Nagios. WIth the help of a system admin (with nagios knowledge) we managed to get the services visible in OPM UI. 
I attached a file with some issues I ran into before. Perhaps they can help others in troubleshooting.

[opm_issues.txt](https://github.com/OPMDG/opm-core/files/231734/opm_issues.txt)

Kind regards.

**Comment by rjuju** [comment]
Yes, Nagios can be quite painful to configure. It's a good news you managed to make it work :)

And thank you very much for the text file, it's really helpful!

I'll integrate it to the documentation soon.

**Comment by lupsups** [comment]
Should nagios be installed and configured on the host to monitor the database?

**Comment by rjuju** [comment]
You can install nagios where you want. You just have to make sure that:

- it can connect to the OPM database to store the perfdata
- it can connect to the monitored server (directly, via NRPE or whatever)

It's usually simpler to configure Nagios and the OPM database on the same server though.

**Comment by lupsups** [comment]
Thanks, I am just testing opm, so I wil configure it on the same server. I am usign a debian 8 as my server, I am new to nagios and opm, sorry for my newbie questions
