### ISSUE TITLE
List of servers per accounts -  No server found.

### ISSUE THREAD

**Issue by satyamsaksham** [OPMDG/opm-core#37]
I installed  [OPM](http://opm.readthedocs.io/opm-core/Installation.html) and [Nagios](https://www.digitalocean.com/community/tutorials/how-to-install-nagios-4-and-monitor-your-servers-on-ubuntu-14-04) in my Machine that using OS Ubuntu 14.04 and PostgreSQL 9.3. I' getting 
No server found, while accessing http://127.0.0.1:3000/.

**Comment by rjuju** [comment]
Hello,

Did you setup hosts and services in Nagios ? Can you check these items to see if there's an issue with your setup: http://opm.readthedocs.io/general/common_problems.html

**Comment by satyamsaksham** [comment]
root@saksham:~# cat <<'EOF' >> /etc/nagios3/commands.cfg
> define command{
>     command_name    process-service-perfdata-file
>     command_line    /bin/mv /var/lib/nagios3/service-perfdata
/var/lib/nagios3/spool/perfdata/service-perfdata.$TIMET$
> }
> define command{
>     command_name    process-host-perfdata-file
>     command_line    /bin/mv /var/lib/nagios3/host-perfdata
/var/lib/nagios3/spool/perfdata/host-perfdata.$TIMET$
> }
> EOF
bash: /etc/nagios3/commands.cfg: No such file or directory

**Comment by satyamsaksham** [comment]
*opm=# SELECT COUNT(*) FROM wh_nagios.hub;*
 count
-------
     0
(1 row)

*opm=# SELECT COUNT(*) FROM wh_nagios.hub_reject;*
 count
-------
     0
(1 row)

*opm=# SELECT wh_nagios.dispatch_record();*
 dispatch_record
-----------------
 (0,0)
(1 row)

There are no files in
/var/lib/nagios3
/var/lib/nagios3/spool/perfdata



*saksham@saksham:/usr/local/src/opm/opm-core/ui$ ps -aux | grep
nagios_dispatcher*
saksham   4143  0.0  0.0  15944  2208 pts/6    S+   13:12   0:00 grep
--color=auto nagios_dispatche
root     31224  0.0  0.1  44360 12876 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31227  0.0  0.1  44352 12804 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31230  0.0  0.1  44352 12960 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31233  0.0  0.1  44352 13044 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31236  0.0  0.1  44392 12800 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31239  0.0  0.1  44352 13040 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31242  0.0  0.1  44360 12908 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31245  0.0  0.1  44360 13032 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31248  0.0  0.1  44396 12836 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31251  0.0  0.1  44360 12800 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf
root     31254  0.0  0.1  44360 13012 ?        Ss   12:04   0:00
/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl -c
/usr/local/etc/nagios_dispatcher.conf


*saksham@saksham:~$ ls -al /var/lib/nagios3/*
total 12
drwxr-xr-x  3 root root 4096 Jul 20 11:55 .
drwxr-xr-x 82 root root 4096 Jul 20 11:55 ..
drwxr-xr-x  3 root root 4096 Jul 20 11:55 spool

**Comment by satyamsaksham** [comment]
Thank you very much for your Reply Julien

**Comment by satyamsaksham** [comment]
I've this */usr/local/nagios/etc/objects/commands.cfg*
and I included these
<http://opm.readthedocs.io/opm-core/Installation.html#nagios-nagios-dispatcher>
commands here.

**Comment by satyamsaksham** [comment]
Thank you very much,

You are right I'm making mistake in this section http://opm.readthedocs.io/opm-core/Installation.html#nagios-and-nagios-dispatcher.
I'm having my hosts now. My next moment is about getting PostgreSQL Status. How can I define service for that.

**Comment by satyamsaksham** [comment]
Thank you very much,

You are right I'm making mistake in this section
http://opm.readthedocs.io/opm-core/Installation.html#nagios-and-nagios-dispatcher
.
I'm having my hosts now. My next moment is about getting *PostgreSQL Status*.
How can I *define service* for that.

**Comment by rjuju** [comment]
You have to define a nagios service for each action of the check_pgactivity probe you want to use.

The list of action is found here: http://opm.readthedocs.io/probes/check_pgactivity.html#services

The postgresql status can be determined by either the "connection" or the "is_master"  actions. These do not generate perfdata, so no graph will be available in OPM UI.

**Comment by satyamsaksham** [comment]
Would you please explain me how to configure
*check_pgactivity ?*I need to monitor the PostgreSQL databases of different
hosts ?

**Comment by satyamsaksham** [comment]
There are the changes I made in *check_pgactivity*

=item B<-s>, B<--service> custom_query
=item B<-U>, B<--username> tad
=item B<-d>, B<--dbname> RIL11MAY107PM
=item B<-S>, B<--dbservice> localdb

*In pg_service.conf*
[
[localdb]
dbname=RIL11MAY107PM
user=tad
]

=item * Parameters C<--host HOST>, C<--port PORT>, C<--user ROLE> or
C<--dbname RIL11MAY107PM>
$args{'dbname'} = $ENV{'PGDATABASE'} || 'RIL11MAY107PM'

**Comment by satyamsaksham** [comment]
Would you please explain me how to configure
*check_pgactivity ?*I need to monitor the PostgreSQL databases of different
hosts ?

There are the changes I made in *check_pgactivity*

=item B<-s>, B<--service> custom_query
=item B<-U>, B<--username> tad
=item B<-d>, B<--dbname> RIL11MAY107PM
=item B<-S>, B<--dbservice> localdb

*In pg_service.conf*
[
[localdb]
dbname=RIL11MAY107PM
user=tad
]

=item * Parameters C<--host HOST>, C<--port PORT>, C<--user ROLE> or
C<--dbname RIL11MAY107PM>
$args{'dbname'} = $ENV{'PGDATABASE'} || 'RIL11MAY107PM'

**Comment by satyamsaksham** [comment]
There are the changes I made in *check_pgactivity*

=item B<-s>, B<--service> custom_query
=item B<-U>, B<--username> tad
=item B<-d>, B<--dbname> RIL11MAY107PM
=item B<-S>, B<--dbservice> localdb

*In pg_service.conf*
[
[localdb]
dbname=RIL11MAY107PM
user=tad
]

=item * Parameters C<--host HOST>, C<--port PORT>, C<--user ROLE> or
C<--dbname RIL11MAY107PM>
$args{'dbname'} = $ENV{'PGDATABASE'} || 'RIL11MAY107PM'

**Comment by satyamsaksham** [comment]
Would you please explain me how to configure check_pgactivity ?
I need to monitor the PostgreSQL databases of different hosts ?

There are the changes I made in check_pgactivity

=item B<-s>, B<--service> custom_query
=item B<-U>, B<--username> tad
=item B<-d>, B<--dbname> RIL11MAY107PM
=item B<-S>, B<--dbservice> localdb

In pg_service.conf
[
[localdb]
dbname=RIL11MAY107PM
user=tad
]

=item * Parameters C<--host HOST>, C<--port PORT>, C<--user ROLE> or
C<--dbname RIL11MAY107PM>
$args{'dbname'} = $ENV{'PGDATABASE'} || 'RIL11MAY107PM'

**Comment by rjuju** [comment]
I can a problem in your configuration:

you should define only one way to access a server. Either using `--dbservice` either using `--username --dbname`, but not both

Did you modify the check_pgactivity script? That's not how it's supposed to be configured, you should define your command in such a way that you can customise the parameters. I can't really advice you a way to configure nagios, because nagios interest is to be really configurable so there are many too achieve what you want, depending on your needs.

If you need advice on how to configure nagios, you should take a look at the documentation: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#service and https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#command and also look for information about check_by_ssh and/or NRPE.

**Comment by satyamsaksham** [comment]
So what I've to do exactly with the check_pgactivity script ?

**Comment by rjuju** [comment]
You should use it as any other probe. If you use NRPE or check_by_ssh, it has to be deployed on every monitored host, if you use local checks you only have to deploy it on the nagios server.

**Comment by satyamsaksham** [comment]
Could you please explain it clearly ?

**Comment by rjuju** [comment]
Using https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#command and check_pop example, if you want to monitor *locally* a *distant postgres cluster*, for instance backends, you'll end up with something like:

```
define command{
	command_name	check_pgactivity_backends
	command_line	/path/to/check_pgactivity -h $HOSTADDRESS$ -s backends -w 80% -c 90%
}
```

and then use this command in a nagios service configuration.

This is all nagios specific configuration, and as I said previously I can't advice you a configuration since it depends on what are your requirements and constraints.

If you're not at all familiar with nagios and still want to use OPM, you could look for a simpler way to configure Nagios. Some tools for this are available here: https://exchange.nagios.org/directory/Addons/Configuration

You can also look at centreon.

**Comment by satyamsaksham** [comment]
command_line /usr/local/nagios/libexec/check_ping -H $HOSTADDRESS$* -w
100.0,90% -c 200.0,60%*

While defining commands what is the Significance of highlighted ones ?

#Ref
<https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/macros.html>

**Comment by satyamsaksham** [comment]
*longest_query, *this is the service I would like to deal with. I need to
define this Service to Monitor my Hosts database and to improvise the time
consuming Queries.

**Comment by rjuju** [comment]
> command_line /usr/local/nagios/libexec/check_ping -H $HOSTADDRESS$* -w 100.0,90% -c 200.0,60%* While defining commands what is the Significance of highlighted ones ?

-w and -c are the warning and critical thresholds, above which the service calling this check will be either un critical or warning status.

**Comment by rjuju** [comment]
> *longest_query, *this is the service I would like to deal with. I need to define this Service to Monitor my Hosts database and to improvise the time consuming Queries.

You'll have to call something like
`/path/to/check_pgactivity -h $HOSTADDRESS$ -s longest_query -w 5m -c 10m`

Warning will be raised if a query is longer than 5 min, and critical if longer than 10.

Also, please note that OPM is a monitoring tool and will therefore only give global overview informations. You can know with OPM that you have long running query, but you need a performance analysis tool to know which are these query and how consuming they're. For this, you can look at http://dalibo.github.io/pgbadger/

**Comment by rjuju** [comment]
I'm closing this issue. Feel free to reopen it if you have more questions.
