### ISSUE TITLE
Graph data is not loading

### ISSUE THREAD

**Issue by saccy** [OPMDG/opm-core#40]
Ive been looking into a postgres monitoring solution and invested a few hours into OPM. I can log in to the UI and can see the servers and their services, but the graphs for the services are blank for both check_pgactivity services and also for the standard nagios services. Nagios has been running for a while so there should be something to see. 

I can see that the check_pgactivity services are running and returning data through nagios. 

The perfdata files are being generated and none of the logs are showing errors. I've tried different web browsers but no luck. 

Version details: 
OPM 2.3
Nagios 4.2.0
Centos7

example of what I see:
![image](https://cloud.githubusercontent.com/assets/15975108/17504149/8fa30156-5e39-11e6-84f2-c5d4bf174551.png)

**Comment by rjuju** [comment]
Hello,

Do you see any javascript error in your browser?  The console can be displayed with F12, at least on firefox and chrome.

**Comment by saccy** [comment]
Hey, turns out this was just an issue with the VM I was using having the wrong time. I was looking for data using my local time through the UI when I should have been looking for a couple days prior. Apologies!
