### ISSUE TITLE
issu with OPM

### ISSUE THREAD

**Issue by fmotnaldo** [OPMDG/opm-core#45]
Hi,

I install the opm feture in nagios server but I got some issue regarding the internal database. 

-bash-4.1$ psql -U postgres -c 'SELECT wh_nagios.dispatch_record ()' opm
ERROR:  schema "wh_nagios" does not exist

I follow the document but I cannot see any server into the oPM web site. I need some help to finish the configuration. 

Thanks

**Comment by rjuju** [comment]
Hello,

Since you also sent a mail with the same problem but some more details, I'll answer the mail and close this issue.

Regards.
