### ISSUE TITLE
Request for Change - Hypnotoad port number configuration

### ISSUE THREAD

**Issue by Postgressor** [OPMDG/opm-core#48]
We currently run OPM version 2.4  with the hynotoad web layer.

As port 8080 is popular with many other products, it would be helpful if a configuration option was added to allow setting a different port number for the OPM web access, perhaps in the OPM.conf file or similar. This is not offered by hypnotoad as a command line parameter, by design.

**Comment by rjuju** [comment]
Indeed, it looks that changing socket port when using hypnotoad requires modification in the application.

I'll work on it shortly.

**Comment by rjuju** [comment]
Sorry for coming back this late.

I read more documentation, and it appears that you can specify hypnotoad specific configuration options in the opm.conf file, per http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Hypnotoad

So, just adding this in my opm.conf file is enough to change the listen port, or whatever hypnotoad configuration setting:

```diff
diff --git a/ui/opm.conf b/ui/opm.conf
index 1d75790..6d6f247 100644
--- a/ui/opm.conf
+++ b/ui/opm.conf
@@ -4,6 +4,11 @@
     "rewrite": 0,
     "base_url" : "http://www.example.com/opm/",
 
+    "hypnotoad" : {
+        "listen" : ["http://*:8090"],
+        "worker" : 10
+    },
+
```

I'll add it in the documentation.
