### ISSUE TITLE
Login demo

### ISSUE THREAD

**Issue by Gaetanbrl** [OPMDG/opm-core#50]
Hello,
I would like to open your [live demo](http://demo.opm.io/login).
I used opm / demo to (login / password) and a wrong message appear. 

Had you change login / password ? 

Thank you;

**Comment by rjuju** [comment]
Hi @Gaetanbrl.

Indeed the password apparently was changed.  I reset it, so connecting with opm // demo, as indicated on the website, should now work.

Can you confirm it works for you?
