### ISSUE TITLE
Setup completed, But opm ui doesn't seem to connect the database properly

### ISSUE THREAD

**Issue by geeluck** [OPMDG/opm-core#8]
I install everything, nagios, opm-core, extension(wh_nagios, hstore)... etc.

And I successfully run the opm web ui with "morbo script/opm" or "hypnotoad -f script/opm"

After login the opm ui with account, Login was succeed. But After I click one menu (like LOAD, PING, HTTP) I see the message ui console.

DBD::Pg::st execute failed: Cannot call execute on a disconnected database handle at /root/opm-core-REL_2_3/ui/script/../lib/Helpers/Menu.pm line 55.
DBD::Pg::st fetchrow_hashref failed: no statement executing at /root/opm-core-REL_2_3/ui/script/../lib/Helpers/Menu.pm line 57.

line 55 is running SQL as follows:

49             if ($level ne "guest" ) {
 50                 $dbh = $self->database();
 51                 $sql = $dbh->prepare(
 52                     "SELECT id, hostname, COALESCE(rolname,'') AS rolname
 53                     FROM public.list_servers()
 54                     ORDER BY rolname, hostname;");
 55                 $sql->execute();

I think that to use "public.list_servers()", SET opm.rolname TO user1;
 (user1 is depend on system)

Doesn't "opm.rolname" SET when the account is logged on?

Please solve the problem... I got some stressed...

**Comment by sivaloga** [comment]
HI geeluck,

Same issue.
mojo version :+1: 
  Perl        (v5.14.2, linux)
  Mojolicious (5.75, Tiger Face)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.84+   (n/a)
  Net::DNS::Native 0.15+  (n/a)
How to downgrade the mojo version.
