### ISSUE TITLE
How can I show PGSQL perf data on OPM UI ?

### ISSUE THREAD

**Issue by geeluck** [OPMDG/opm-core#9]
I successfully installed OPM with @rjuju 's help.
So, I can monitor Postgres Server's basic Perf data, like Current Load, Current Users, Host, Http, Ping, SSH...etc.

In demo, I show the PGSQL Perf data like Backends, Bgwriter, Database Size, Hit ratio, Locks, Longest Query, Ready archives, table bloat.

But, in my site there aren't above perf data.

On Installation Guide (http://opm.readthedocs.org/opm-core/Installation.html) 
There is check_pgactivity Tool. 

To run check_pgactivity regularly on cron job, and I make PGSQL perf data to file.
After that, modify nagios_dispatcher.pl code and load the perfdata to wh_nagios Storage on Postgres?

I think there is a easy and quick guide.
Please let me know.

Thank you in advance.

**Comment by gilcorn** [comment]
Hi geeluck, Would you please tell me what command you added to command config for check_pgactivity?
